### ISSUE TITLE
part of the buttons not responding

### ISSUE THREAD

**Issue by anusche** [gwygonik/SquiggleDraw#19] opened 2022-02-12 15:04 UTC
I have just installed SquiggleDraw and have limited access to make adjustments.  I can only adjust "number of lines", "invert colors" and "connect ends". Is there anything special, I need to pay attention to?

**Comment by jainkila** [comment] 2022-03-15 15:08
Same issue here.
Processing 4.0b7, ControlP5 2.2.6, Linux Mint 20.2 Cinnamon. It was about 6 months ago with older os setup this worked fine. I don't know what has changed.

**Comment by oskay** [comment] 2022-03-15 16:18
Were you using Processing 3 previously, perhaps?

**Comment by jainkila** [comment] 2022-03-15 16:23
I installed Processing 3.5.4. Now buttons work.

**Comment by gwygonik** [comment] 2022-03-20 03:05
I have been able to reproduce the issue in Processing 4.0b7 and have found what the root cause is. 

The initial app window is set to be 100x100 pixels, and resized after loading the starting image. The problem is that **interactions with the app only work within the initial 100x100px area**, even though the window is much larger.

The workaround is to set the initial window to a larger size to encompass all the UI (line 69):

`size(300, 1000);`

I hesitate to check this in because it definitely feels like a bug in Processing, not this sketch. I will be opening an issue in the Processing repo as soon as I can put a small working example together.

**Comment by oskay** [comment] 2022-03-20 03:17
Maybe put that fix in a "Processing V4" branch?

**Comment by gwygonik** [comment] 2022-03-20 04:10
Created issue in Processing 4 repo: https://github.com/processing/processing4/issues/452

Will work on making new "Processing V4" branch in next couple of days.

**Comment by oskay** [comment] 2023-01-09 21:00
Looks like the Processing issue was closed, and the presumably-related [ControlP5 issue](https://github.com/sojamo/controlp5/issues/175) is not active. 

The workaround appears to work for me. Maybe add that V4 branch?

**Comment by gwygonik** [comment] 2023-01-23 16:53
Sorry - been dealing with life stuff (layoff). Will get an update pushed soon.

**Comment by oskay** [comment] 2023-01-23 17:07
I'm so sorry to hear that. Take care of yourself first.

**Comment by verstecken** [comment] 2023-01-28 10:01
setting `size(300, 1000);` in setup(), like written above, fixes the problem of not responding sliders. thanks!

**Comment by gwygonik** [comment] 2023-01-28 19:01
To follow-up with this, I'll push a general update soon just incorporating the `size()` update; no need for a V4 branch as this doesn't impact V3.

Also, I haven't been _totally_ wallowing in misery since being laid off 😉 . I've been trying to find a replacement for ControlP5 since it is no longer maintained and the root of this particular bug is deep in the way it was set up (and potentially using undocumented features per the issue tracking with P5). The other existing GUI libraries for P5 are either lacking needed controls or are as old or older than controlP5 and also not maintained. I wrote a GUI library for Flash 20 years ago and I don't want to do that again 😜 .

I also really want to update the look and feel of the UI as there are some UX annoyances, like the toggle button state is VERY ambiguous and requires toggling to tell if it's on or off (side note: the toggle button _does_ have the experimental controlP5 setting to use images, but doing so breaks the label appearing ☹️ )

But I'll keep it simple.

**Comment by gwygonik** [comment] 2023-01-28 20:00
Updated with fix and new toggle buttons. I used image buttons but that required creating and adding separate label controls with non-default font setting. Will close this! 😄

**Closed as completed by gwygonik** 2023-01-28 20:00 UTC
